
public class MIDI_instruments {
	public String list[]={
		    "Piano acoustique 1",
		    "Piano acoustique 2",
		    "Grand piano électrique",
		    "Piano Honky-tonk",
		    "Piano électrique 1",
		    "Piano électrique 2",
		    "Clavecin",
		    "Clavicorde",
		    "Célesta",
		    "Carillon",
		    "Boîte à musique",
		    "Vibraphone",
		    "Marimba",
		    "Xylophone",
		    "Cloches tubulaires",
		    "Tympanon",
		    "Orgue à tubes",
		    "Orgue percussif",
		    "Orgue rock",
		    "Orgue d'Eglise",
		    "Orgue vibrato",
		    "Accordéon",
		    "Harmonica",
		    "Accordéon tango",
		    "Guitare acoustique nylon",
		    "Guitare acoustique acier",
		    "Guitare électrique jazz",
		    "Guitare électrique pure",
		    "Guitare électrique sourdine",
		    "Guitare électrique saturée",
		    "Guitare élec. à distorsion",
		    "Guitare élec. - harmonique",
		    "Basse acoustique",
		    "Basse électrique 1",
		    "Basse électrique 2",
		    "Basse électrique 3",
		    "Bass slap 1",
		    "Bass slap 2",
		    "Basse synthétiseur 1",
		    "Basse synthétiseur 2",
		    "Violon",
		    "Viole",
		    "Violoncelle",
		    "Contrebasse",
		    "Cordes trémolo",
		    "Cordes pizzicato",
		    "Harpe",
		    "Timbales",
		    "Quartet cordes 1",
		    "Quartet cordes 2",
		    "Cordes synthétiseur 1",
		    "Cordes synthétiseur 2",
		    "Choeurs aahs",
		    "Voix oohs",
		    "Voix synthétiseur",
		    "Coup d'orchestre",
		    "Trompette",
		    "Trombone",
		    "Tuba",
		    "Trompette bouchée",
		    "Cors",
		    "Ensemble de cuivres",
		    "Cuivres synthétiseur 1",
		    "Cuivres synthétiseur 2",
		    "Saxophone soprano",
		    "Saxophone alto",
		    "Saxophone ténor",
		    "Saxophone baryton",
		    "Hautbois",
		    "Cors anglais",
		    "Basson",
		    "Clarinette",
		    "Piccolo",
		    "Flûte",
		    "Flûte à bec",
		    "Flûte de pan",
		    "Bouteille sifflée",
		    "Shakuhachi",
		    "Sifflet",
		    "Ocarina",
		    "Signal carré (Lead 1)",
		    "Signal dent de scie (Lead 2)",
		    "Orgue à vapeur (Lead 3)",
		    "Chiff (Lead 4)",
		    "Charang (Lead 5)",
		    "Voix (Lead 6)",
		    "Quinte (Lead 7)",
		    "Introduction bass (Lead 8)",
		    "New age (pad 1)",
		    "Warm (pad 2)",
		    "Synthé. polyphonique (pad 3)",
		    "Choeurs (pad 4)",
		    "Archet (pad 5)",
		    "Métallique (pad 6)",
		    "Halo (pad 7)",
		    "Glissement (pad 8)",
		    "Pluie (fx 1)",
		    "Bande sonore (fx 2)",
		    "Cristal (fx 3)",
		    "Atmosphère (fx 4)",
		    "Brightness (fx 5)",
		    "Goblins (fx 6)",
		    "Echoes (fx 7)",
		    "Sci-fi (fx 8)",
		    "Sitar",
		    "Banjo",
		    "Shamisen",
		    "Koto",
		    "Kalimba",
		    "Cornemuse",
		    "Violon",
		    "Shanai",
		    "Sonnerie",
		    "Agogo",
		    "Percussion en acier",
		    "Woodblock",
		    "Taiko drum",
		    "Tom Mélodique",
		    "Percussion synthétique",
		    "Cymbale inversée",
		    "Touchette de guitare",
		    "Respiration",
		    "Vague",
		    "Chants d'oiseaux",
		    "Sonnerie de téléphone",
		    "Hélicoptère",
		    "Applaudissements",
		    "Coup de feu"
	};
}
